- drm_info.c
These are flags from `DRM_CLIENT_CAP_STEREO_3D` and `DRM_CLIENT_CAP_ASPECT_RATIO`.
Some regular flags were removed, because they're marked as deprecated: https://elixir.bootlin.com/linux/latest/source/include/uapi/drm/drm_mode.h#L41
Fixes #13
> Add support for more mode flags

- drm_info.c
This is useful to know if some blobs are set or unset (zero blob ID).
> Print blob IDs

- drm_info.h
- json.c
- main.c
Allows explicitly selecting the devices you look at with command line arguments, in case you only want to look at one, instead of them all.
Also adds some extra error-handling in some cases where we're given an invalid file.
> Explicit arguments

- pretty.c
In case a new format/modifier is added to libdrm, we can still work out what the format actually is instead of simply getting "unknown".
> Print hex for format/modifier

- .gitignore
- compat.h
- json.c
- main.c
- meson.build
- pretty.c
- subprojects/json-c.wrap
Adds a meson wrap for building json-c where we don't have 0.13, plus some other cleanup for libdrm defines.
Also, apparently json-c intends people to use <json.h> with -I${prefix}/include/json-c, as that's what their pkg-config and documentation says, so this also swaps over to that. It's also needed for the subproject to work.
> Fix build on Debian stable

- json.c
Previously the "value" field of a property object was automatically
filled with the raw uint64_t value by default. In particular, this
happened for blobs.
However I'd like to reserve the "value" field for blobs to contain
the base64-encoded blob contents. If we fill this with a uint64_t
value now, we won't be able to change it to a string later without
breaking consumers.
Additionally, this causes issues for future property types: they
would have their "value" field set to the uint64_t value too, making
it difficult to change it to a more appropriate type later.
> Remove default case from property "value" marshalling

- subprojects/json-c.wrap
I've submitted the json-c wrap upstream and it was just merged.
So we can use that instead of my own repo.
> Update json-c wrap to upstream wrapdb URL

- fourcc.py
- meson.build
- pretty.c
This eliminates the need to maintain a list of formats used
for converting from fourcc codes to the prettier version by
parsing drm_fourcc.h directly and building a header for use
in pretty.c
> Dynamically generate format lookup table from drm_fourcc header

- fourcc.py
The regex matching formats and modifiers were reading ahead to
a nonexistent condition since the code was reading one line at
a time. Fix this by reading the entire file into a string and
parsing it from there. This effectively adds *_GOB mod formats.
> fourcc: Search entire file instead of one line at a time

- json.c
- pretty.c
Some drivers (e.g. Nouveau) don't support atomic, so we can't rely on properties to retrieve e.g. the current mode.
> Add support for legacy fields

- meson.build
See build log [before](https://github.com/ascent12/drm_info/files/3489542/drm_info-2.1.0.7.log) and [after](https://github.com/ascent12/drm_info/files/3489541/drm_info-2.1.0.8.log).
> Drop dependency on python3 symlink

- meson.build
Tried to build with 0.45, fails because the python module has been introduced
in 0.46.
> Specify minimum Meson version

- main.c
When no DRM devices are detected, drm_info fails with:
drmGetDevices: No such file or directory
And then segfaults. This happens because the drm_info() function returns
a NULL pointer on failure but main() doesn't handle it.
> Fix segfault on drmGetDevices failure

- subprojects/json-c.wrap
wrapdb.mesonbuild.com is down. GitHub should be more reliable. The file
is exactly the same.
> build: download json-c wrap patch from GitHub

- json.c
And remove extraneous checks for zero object IDs. See [1].
[1]: https://github.com/ascent12/drm_info/pull/46#discussion_r365556824
> Handle all drmMode* errors

- json.c
- pretty.c
Currently the USB bus type parsing is broken in libdrm, at least for the devices I have. drmGetDevice fails with -EINVAL.
Already submitted a libdrm MR to fix it: https://gitlab.freedesktop.org/mesa/drm/merge_requests/45
> Add support for USB bus types

- pretty.c
Fixes #51
The libpci functions can crash if this is not called.
> Call pci_init after pci_alloc

- pretty.c
Older drivers don't expose the GAMMA_LUT_SIZE property. Print the legacy
drmModeCrtc.gamma_size field to account for those.
> Print legacy CRTC gamma size

- pretty.c
The kernel sets the enum values to the number of left shifts, the enum
values aren't bits we can use directly.
See for instance drm_plane_create_rotation_property [1].
[1]: https://cgit.freedesktop.org/drm-tip/tree/drivers/gpu/drm/drm_blend.c#n282
> Fix bitmask pretty-printing

- json.c
- pretty.c
Allows to figure out whether a device is render-only or not.
> Print available nodes

- meson.build
- modifiers.c
- subprojects/libdrm.wrap
~~Depends on https://github.com/ascent12/drm_info/pull/60~~
It's not possible in practice to explicitly enumerate all modifiers, because they are very complicated. Instead, rely on drm_fourcc.h macros and manually format a string.
Closes: #62
cc @bnieuwenhuizen
> Add support for AMD modifiers

- fourcc.py
- modifiers.c
Instead of enumerating all cases with a powerset via code generation,
parse the ARM modifiers manually just like the other modifiers.
> Manually parse ARM AFBC modifiers

- json.c
- pretty.c
Some drivers (nouveau, radeon) don't have the FB_ID property, because
they aren't atomic. We can still display the legacy FB information in
this case.
> Print plane legacy FB

- pretty.c
Some APIs describe the pitch in pixels, some APIs describe it in
bytes. Make it clear that KMS uses bytes.
> Print unit for pitch

- json.c
drmModeGetConnector performs an active probe on older kernels.
The drmModeGetConnectorCurrent variant doesn't mutate the kernel
state. Since [1], drmModeGetConnector will be demoted to
drmModeGetConnectorCurrent if the client isn't DRM master.
Since we should never be DRM master, align our expectations with
the latest kernel.
[1]: https://cgit.freedesktop.org/drm/drm-misc/commit/?id=8f86c82aba8b13e732cfdd6d0e19a7dd48197e43
> Use drmModeGetConnectorCurrent

- pretty.c
It's a bit confusing to look at all of the info and see that some
fields are duplicated in the props, and some even have a different
value like the gamma size (!). Let's clearly label legacy info as
such.
> Group legacy info
